# Generated by Django 3.1.2 on 2021-12-20 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20211220_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fechaAlta',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='fechaAlta'),
        ),
    ]
