# Generated by Django 3.1.2 on 2022-01-20 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=60, verbose_name='apellidos')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('biografia', models.CharField(max_length=255, verbose_name='biografia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='idUsuario')),
            ],
        ),
    ]
