# Generated by Django 3.1.2 on 2022-02-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220128_1226'),
        ('project', '0003_auto_20220126_2232'),
    ]

    operations = [
    ]
