# Generated by Django 3.1.2 on 2022-01-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220110_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
    ]
