# Generated by Django 3.1.2 on 2022-01-13 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fechaAlta',
            field=models.DateField(default=datetime.date(2022, 1, 13), verbose_name='fechaAlta'),
        ),
    ]
