# Generated by Django 3.1.2 on 2022-01-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220113_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='activo'),
        ),
    ]
