# Generated by Django 3.1.2 on 2022-01-20 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220113_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fechaAlta',
            field=models.DateField(default=datetime.date(2022, 1, 20), verbose_name='fechaAlta'),
        ),
    ]
