# Generated by Django 3.1.2 on 2022-01-24 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20220120_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fechaAlta',
            field=models.DateField(default=datetime.date(2022, 1, 24), verbose_name='fechaAlta'),
        ),
    ]
